version: '3.9'
services:
  bili_task:
    build: ..
    image: catlair/bili-test-local-img
    container_name: bili_task
    volumes:
      - ../config/:/usr/src/app/config/
      - ../logs/:/usr/src/app/logs/
    tty: true
    env_file: ../.env
    user: root
    cap_add:
      - SYS_ADMIN
