name: bilibili-task

on:
  workflow_dispatch: # 手动触发
  # schedule: # 计划任务触发
  # - cron: '5 15 * * *'
  # cron表达式，时区是UTC时间，比我们晚8小时，要用我们的时间减去8小时后填上去，如上所表示的是每天23点5分
  # 建议每个人都修改下时间！不要使用默认时间！最好不要设定在整点，错开峰值，避免大量G站同一个IP在相同时间去请求B站接口，导致IP被禁！

jobs:
  run-bilibili-tool:
    runs-on: ubuntu-latest

    environment: Production

    steps:
      # 判断是否暂停运行
      - name: isStop ?
        env:
          STOP_RUN: ${{secrets.STOP_RUN}}
        run: |
          if [ $STOP_RUN ]; then
          echo "用户设置停止运行程序"
          exit -1
          fi

      # 输出IP
      - name: IP
        run: sudo curl ifconfig.me

      # 设置服务器时区为东八区
      - name: Set time zone
        run: sudo timedatectl set-timezone 'Asia/Shanghai'

      # 检出
      - name: Checkout
        uses: actions/checkout@v2

      # 运行
      - name: Run APP
        run: sudo docker run --env BILI_COOKIE="${{ secrets.BILI_COOKIE }}" -v $(pwd)/config/:/usr/src/app/config/ -i --rm --user root --cap-add=SYS_ADMIN catlair/bilitaskpuppeteer node ./dist/index.js
