name: build docker
on:
  workflow_dispatch: # 手动触发
  release:
    types: [published]
jobs:
  build:
    if: github.repository == 'catlair/bili-task-puppeteer'
    runs-on: ubuntu-latest
    environment: Build
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: set Docker tag
        run: echo MY_TAGS=${{ github.ref  }} | sed -e "s/refs\/tags\/v//g"  >> $GITHUB_ENV

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: catlair/bilitaskpuppeteer:latest,catlair/bilitaskpuppeteer:${{ env.MY_TAGS }}
