name: build chromium env
on:
  workflow_dispatch: # 手动触发
jobs:
  build:
    if: github.repository == 'catlair/bili-task-puppeteer'
    runs-on: ubuntu-latest
    environment: Build
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          file: docker/Dockerfile.alpine-chromium
          tags: catlair/alpine-chromium:latest,catlair/alpine-chromium:${{ secrets.BUILD_CHROMIUM_VERSION }}
