name: build docker
on:
  workflow_dispatch: # 手动触发
  release:
    types: [published]
jobs:
  build:
    if: github.repository == 'catlair/bili-task-puppeteer'
    runs-on: ubuntu-latest
    environment: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: set Docker tag
        run: echo MY_TAGS=${{ github.ref  }} | sed -e "s/refs\/tags\/v//g"  >> $GITHUB_ENV

      # 这会加快编译速度，但也会增加镜像大小
      # - name: Preparation
      #   run: |
      #     echo '!node_modules' >> .dockerignore
      #     echo '!dist' >> .dockerignore
      #     sed -i '14,18d' Dockerfile
      #     echo '"${{ env.MY_TAGS }}"' > src/config/level.json

      # 用上面的不用这
      - name: Preparation
        run: |
          echo '"${{ env.MY_TAGS }}"' > src/config/level.json

      # - name: Use Node.js 14.x
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: 14.x

      # - name: install and build
      #   run: |
      #     npm install
      #     npm run build
      #     npm prune --production

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: catlair/bilitaskpuppeteer:latest,catlair/bilitaskpuppeteer:${{ env.MY_TAGS }}
