name: build chromium env
on:
  workflow_dispatch: # 手动触发
jobs:
  build:
    if: github.repository == 'catlair/bili-task-puppeteer'
    runs-on: ubuntu-latest
    environment: Build
    steps:
      - uses: actions/checkout@master
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: catlair/alpine-chromium
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: docker/Dockerfile.alpine-chromium
          tags: 'latest,${{ secrets.BUILD_CHROMIUM_VERSION }}'
